In [1]:
import numpy as np

array = np.array([1,2,3,4,5,6])

print(array)

[1 2 3 4 5 6]


In [2]:
import numpy as np

array = np.array(["Ama", "Addo", "Kofi"])

print(array.ndim)

1


In [3]:
import numpy as np

array = np.array([["Ama", "Addo", "Kofi"], ["Ama", "Addo", "Kofi"]])

print(array.ndim)

2


In [4]:
import numpy as np

array = np.array([["Ama", "Addo", "Kofi"], ["Ama", "Addo", "Kofi"]])

print(array.shape)

(2, 3)


In [5]:
import numpy as np

array = np.array([["Ama", "Addo", "Kofi"], ["Ama", "Addo", "Kofi"]])

print(array[0][0])

Ama


In [13]:
import numpy as np

array = np.array([[[1,2,3,4,5], 
                   [6,7,8,9,10], 
                   [12,13,14,15,16]]])

print(array[0:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [12 13 14 15 16]]]


In [14]:
import numpy as np

array = np.array([3,4,5,6,6])

print(array + 4)
print(array / 4)
print(array - 4)
print(array * 4)
print(array ** 4)

[ 7  8  9 10 10]
[0.75 1.   1.25 1.5  1.5 ]
[-1  0  1  2  2]
[12 16 20 24 24]
[  81  256  625 1296 1296]


In [17]:
import numpy as np

array1 = np.array([3,4,5])
array2 = np.array([9,2,7])

print(array1 - array2)
print(array1 + array2)
print(array1 / array2)

[-6  2 -2]
[12  6 12]
[0.33333333 2.         0.71428571]


In [18]:
import numpy as np

scores = np.array([3,4,5,6])

print(scores == 5)

[False False  True False]
