In [1]:
import numpy as np

array = np.array([1,2,3,4,])
print(array)

[1 2 3 4]


In [3]:
import numpy as np

array = np.array(["A", "B", "C"])
print(array.ndim)

1


In [ ]:
import numpy as np

array = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"] ])
print(array.ndim)

2


In [6]:
import numpy as np

array = np.array([[["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"] ]])
print(array.shape)

(1, 3, 3)


In [7]:
import numpy as np

array = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"] ])
print(array[0][0][0])

A


In [9]:
import numpy as np

array = np.array([["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"] ])
print(array[0,0])

A


In [11]:
word = array[0,0] + array[2,0] 
print(word) 

AG


In [3]:
import numpy as np

array = np.array([[1,2,3,4,],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]

# print(array[0:3])
print(array[0:2, 0:2])


[[1 2]
 [5 6]]


In [4]:
import numpy as np

#Scalar arithematic
array = np.array([1,2,3])

print(array + 1)
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [7]:
import numpy as np

#Vectorized math functions
array = np.array([1.01,2.5,3.99])

print(np.sqrt(array))
print(np.ceil(array))
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[2. 3. 4.]
3.141592653589793


In [8]:
import numpy as np

#exercise
radii = np.array([1,2,3])

print(np.pi * radii ** 2)


[ 3.14159265 12.56637061 28.27433388]


In [11]:
import numpy as np

#Element-wise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
import numpy as np

# comparison operations

scores = np.array([55, 55, 88, 100, 44, 82, 34])

print(scores == 100)

[False False False  True False False False]


In [ ]:
import numpy as np

#broadcasting

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [18]:
import numpy as np

#aggragate functions

array = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.sum(array, axis=0))

55
5.5
[ 7  9 11 13 15]


In [ ]:
import numpy as np

# filtering 

ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])

teenagers = ages[ages < 18]
adults = ages[(ages < 18) & (ages < 65)]

print(teenagers)
print(adults)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]


In [ ]:
import numpy as np

#random numbers
rng = np.random.default_rng()
print(rng.integers(1, 7))

5


In [ ]:
import numpy as np

#floating points numbers
print(np.random.uniform(3))

In [ ]:
import numpy as np

rng = np.random.default_rng()

array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)